import { z } from 'zod';
import { FormFillType, RequestType } from '../../types/enums';
import { LeadGenConstants } from '../../config/constants';

export const ContactRequestSchema = z.object({
  name: z.string().max(128).optional(),
  firstName: z.string().max(40).optional(),
  lastName: z.string().max(80).optional(),
  emailId: z.string().max(LeadGenConstants.EMAIL_ID_MAX_LENGTH).optional(),
  encryptedLeadEmailId: z.string().optional(),
  phone: z.string().max(30).optional(),
  encryptedLeadPhone: z.string().optional(),
  mobilePhone: z.string().max(30).optional(),
  title: z.string().optional(),
  department: z.string().optional(),
  seniority: z.string().optional(),
  industry: z.string().max(100).optional(),
  businessAddress: z.string().max(500).optional(),
  type: z.array(z.string()).optional(),
  category: z.string().max(100).optional(),
  salesRepEmailIds: z.array(z.string()).optional(),
  businessName: z.string().max(250).optional(),
  businessPhone: z.string().max(50).optional(),
  businessNumber: z.string().optional(),
  businessLocations: z.string().max(20).optional(),
  businessEmployees: z.string().max(20).optional(),
  numberOfEmployees: z.number().int().optional(),
  monthlyCustomers: z.string().max(10).optional(),
  annualRevenue: z.number().optional(),
  locationsUnderManagement: z.string().max(50).optional(),
  customerMonthlyExpenditure: z.string().max(50).optional(),
  productToSell: z.array(z.string()).optional(),
  productOfInterest: z.array(z.string()).optional(),
  website: z.string().max(500).optional(),
  businessEnv: z.string().optional(),
  crmInfo: z.string().max(50).optional(),
  crmName: z.string().max(50).optional(),

  street: z.string().max(255).optional(),
  city: z.string().max(50).optional(),
  state: z.string().max(50).optional(),
  country: z.string().max(100).optional(),
  countryCode: z.string().max(25).optional(),
  zip: z.string().max(10).optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
  placeId: z.string().max(40).optional(),

  fromGoogle: z.number().int().min(0).max(1).optional(),
  profileUrl: z.string().max(100).optional(),
  googleReviewCount: z.number().int().optional(),
  googleRating: z.number().optional(),

  leadCampaign: z.string().max(250).optional(),
  leadSubCampaign: z.string().max(250).optional(),
  leadCampaignKW: z.string().max(255).optional(),
  leadContent: z.string().max(255).optional(),
  leadMedium: z.string().max(255).optional(),
  leadSource: z.string().max(20).optional(),
  leadSfdcCampaign: z.string().max(50).optional(),
  intent: z.string().max(100).optional(),
  buyingIntent: z.string().max(50).optional(),
  clickUrl: z.string().optional(),
  leadUrl: z.string().optional(),
  clickPageType: z.string().max(100).optional(),
  leadPageType: z.string().max(100).optional(),

  leadOwner: z.string().max(25).optional(),
  sfdcContactId: z.string().max(40).optional(),

  requestType: z.nativeEnum(RequestType).default(RequestType.CONTACT),
  formFillType: z.string().transform((val) => val.toUpperCase()).pipe(z.nativeEnum(FormFillType)).default(FormFillType.MANUAL),
  formFillId: z.string().max(40).optional(),
  visitId: z.string().max(50).optional(),
  sessionId: z.string().max(50).optional(),
  remoteIp: z.string().max(50).optional(),
  deviceName: z.string().max(20).optional(),
  beCta: z.string().max(300).optional(),
  adClickId: z.string().max(255).optional(),
  croExperiments: z.array(z.string()).optional(),

  pageURL: z.string().optional(),
  slug: z.string().optional(),
  eventDate: z.string().optional(),
  eventEndDate: z.string().optional(),
  startTime: z.string().optional(),
  endTime: z.string().optional(),
  timezone: z.string().optional(),
  duration: z.union([z.string(), z.number().transform(String)]).optional(),
  meetingId: z.string().optional(),
  calendarEventId: z.string().optional(),
  organiserEmailId: z.string().optional(),
  additionalAttendees: z.array(z.string()).optional(),
  audienceUrl: z.string().optional(),

  skipLead: z.boolean().optional(),
  skipEmailValidation: z.boolean().optional(),
  skipPhoneValidation: z.boolean().optional(),
  skipBusinessNameValidation: z.boolean().optional(),
  skipLeadLimitValidation: z.boolean().optional(),
  skipZoomInfoProcess: z.boolean().optional(),
  skipMarketoProcess: z.boolean().optional(),
  freemiumRequest: z.boolean().optional(),
  supportSkipLead: z.boolean().optional(),
  upsellRequest: z.boolean().optional(),
  futureWebinar: z.boolean().optional(),
  forcefulLead : z.boolean().optional(),

  comments: z.string().optional(),
  referralCode: z.string().optional(),
  searchAiReportId: z.string().optional(),
  remoteIpCountryName: z.string().optional(),
  remoteIpCountryIsoCode: z.string().optional(),
});

export type ContactRequestDto = z.infer<typeof ContactRequestSchema>;