export const JobNames = {
  LEAD_GENERATION_PROCESS: 'LEAD_GENERATION_PROCESS',
  BUSINESS_AND_LEAD_CREATE: 'BUSINESS_AND_LEAD_CREATE',
  BUSINESS_AGGREGATION: 'BUSINESS_AGGREGATION',
  CALENDAR_LEAD_TEXT: 'CALENDAR_LEAD_TEXT',
  PUSH_SFDC_LEAD_FORCEFUL: 'PUSH_SFDC_LEAD_FORCEFUL',
  PUSH_SKIP_LEAD: 'PUSH_SKIP_LEAD',
} as const;

export type JobName = (typeof JobNames)[keyof typeof JobNames];
